version: 2.4.3.{build}

os: Visual Studio 2019

assembly_info:
  patch: true
  file: OpenTween\Properties\AssemblyInfo.cs
  assembly_file_version: '{version}'

build:
  project: OpenTween.sln
  verbosity: minimal

cache:
  - ./packages/

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore
  - choco install opencover.portable

test_script:
  - OpenCover.Console.exe -register -target:"%xunit20%\xunit.console.exe" -targetargs:".\OpenTween.Tests\bin\Debug\net472\OpenTween.Tests.dll -noshadow -appveyor" -filter:"+[OpenTween*]* -[OpenTween.Tests]*" -excludebyfile:"*.Designer.cs" -skipautoprops -hideskipped:All -returntargetcode -output:coverage.xml

after_test:
  - npm install codecov --save
  - ./node_modules/.bin/codecov -f coverage.xml

  - ps: |
      $env:PATH = $env:PATH + ';C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\'
      $binDir = '.\OpenTween\bin\' + $env:CONFIGURATION + '\'
      $objDir = '.\OpenTween\obj\' + $env:CONFIGURATION + '\'
      $assemblyInfo = '.\OpenTween\Properties\AssemblyInfo.cs'
      $destPath = 'OpenTween_dev-' + $env:APPVEYOR_BUILD_NUMBER + '.zip'
      .\tools\build-zip-archive.ps1 -BinDir $binDir -ObjDir $objDir -AssemblyInfo $assemblyInfo -DestPath $destPath

# vim: et fenc=utf-8 sts=2 sw=2 ts=2
